--[[
    crimson_arena/config.weapons.lua

    THE WEAPON CATALOGUE, and nothing else.

    It lives in its own file because of what it is rather than what it does:
    a list of ninety-odd blocks that an operator scrolls PAST every time they
    want to change a timer, a payout or a spawn. Moving it out is not a
    behaviour change -- this file is loaded straight after config.lua, into
    the same `Config` table, and every rule about these entries is written in
    the block comment below exactly as it was.

    LOAD ORDER IS LOAD-BEARING. config.lua defines `Config.Loadouts`, and the
    line below writes one key into it. fxmanifest.lua lists config.lua first
    for that reason; swapping them raises on a nil index at start-up.
]]

-- THE WEAPON LIST.
--
-- ADD AND REMOVE FREELY. Paste a block in and it appears in the picker at
-- the next restart; delete one and it is gone from the arena for everybody,
-- including anyone whose panel was still showing it -- the server checks
-- every request against this list before it hands out a single round, so a
-- weapon that is not here cannot be obtained by asking for it.
--
-- `enabled = false` does exactly the same as deleting, while keeping the
-- entry to switch back on later. There is no difference the player can see.
--
-- COPY THIS TO ADD ONE:
--
--     {
--         key = 'microsmg',                 -- unique; the panel and wire use it
--         weapon = 'WEAPON_MICROSMG',       -- the real GTA name; this is what is given
--         label = 'Micro SMG',              -- what the player reads
--         category = 'automatic',           -- a key from `categories` above
--         enabled = true,
--         ammo = { default = 120, options = { 60, 120, 250 }, max = 400 },
--         components = {},
--         tint = 0,
--     },
--
-- Two keys the same, or an ammo option above that weapon's own max, are
-- named in the server console at startup rather than failing quietly in
-- front of a player.
--
--   key      -- what the panel and the wire use. Must be unique.
--   weapon   -- the real GTA weapon name. This is what is actually given.
--   ammo     -- default/options/max, see the note above this table.
--   enabled  -- false hides it everywhere without deleting the entry.
Config.Loadouts.weapons = {
    -- GENERATED FROM THIS SERVER'S OWN ox_inventory weapons.lua.
    --
    -- Every entry below is a weapon that really exists in this server's
    -- inventory, and every `item` in an `ammoTypes` line is the ammo item
    -- that weapon's own `ammoname` field names. Neither was guessed: a
    -- weapon the inventory does not define cannot be handed out, and an
    -- ammo item it does not define cannot be given, so both are read from
    -- the source rather than from a list of what GTA usually calls things.
    --
    -- `ammoTypes` is per weapon here rather than one shared list, because
    -- on this server the round differs by weapon -- a 9mm and a 12 gauge
    -- are separate items. That is exactly the per-weapon override the
    -- note further down describes.
    --
    -- ENABLED = FALSE ON EXPLOSIVES, LAUNCHERS AND NOVELTIES. They are
    -- present so they can be switched on deliberately, rather than absent

    -- ---- SIDEARM ---------------------------------------------------
    {
        key = 'acidspray',
        weapon = 'WEAPON_ACIDSPRAY',
        label = '200ML Acid Spray',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '1Ml acid ammo', item = 'ammo-acidspray' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pepperspray',
        weapon = 'WEAPON_PEPPERSPRAY',
        label = '200ML Pepper Spray',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '1Ml pepper ammo', item = 'ammo-pepperspray' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pinkpepperspray',
        weapon = 'WEAPON_PINKPEPPERSPRAY',
        label = '200ML Pepper Spray',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '1Ml pepper ammo', item = 'ammo-pepperspray' } },
        components = {},
        tint = 0,
    },
    {
        key = 'spraypaint',
        weapon = 'WEAPON_SPRAYPAINT',
        label = '200ML Spray Paint',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '1Ml Spray Paint', item = 'ammo-spraypaint' } },
        components = {},
        tint = 0,
    },
    {
        key = 'appistol',
        weapon = 'WEAPON_APPISTOL',
        label = 'AP Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'ceramicpistol',
        weapon = 'WEAPON_CERAMICPISTOL',
        label = 'Ceramic Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'combatpistol',
        weapon = 'WEAPON_COMBATPISTOL',
        label = 'Combat Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'doubleaction',
        weapon = 'WEAPON_DOUBLEACTION',
        label = 'Double Action Revolver',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.38 LC', item = 'ammo-38' } },
        components = {},
        tint = 0,
    },
    {
        key = 'flaregun',
        weapon = 'WEAPON_FLAREGUN',
        label = 'Flare Gun',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = 'Flare round', item = 'ammo-flare' } },
        components = {},
        tint = 0,
    },
    {
        key = 'heavypistol',
        weapon = 'WEAPON_HEAVYPISTOL',
        label = 'Heavy Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.45 ACP', item = 'ammo-45' } },
        components = {},
        tint = 0,
    },
    {
        key = 'machinepistol',
        weapon = 'WEAPON_MACHINEPISTOL',
        label = 'Machine Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'marksmanpistol',
        weapon = 'WEAPON_MARKSMANPISTOL',
        label = 'Marksman Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.22 Long Rifle', item = 'ammo-22' } },
        components = {},
        tint = 0,
    },
    {
        key = 'nailgun',
        weapon = 'WEAPON_NAILGUN',
        label = 'Nail Gun',
        category = 'sidearm',
        enabled = false,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = 'Nail Ammo', item = 'ammo-nail' } },
        components = {},
        tint = 0,
    },
    {
        key = 'navyrevolver',
        weapon = 'WEAPON_NAVYREVOLVER',
        label = 'Navy Revolver',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.44 Magnum', item = 'ammo-44' } },
        components = {},
        tint = 0,
    },
    {
        key = 'gadgetpistol',
        weapon = 'WEAPON_GADGETPISTOL',
        label = 'Perico Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pistol',
        weapon = 'WEAPON_PISTOL',
        label = 'Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pistol50',
        weapon = 'WEAPON_PISTOL50',
        label = 'Pistol .50',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.50 AE', item = 'ammo-50' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pistolmk2',
        weapon = 'WEAPON_PISTOL_MK2',
        label = 'Pistol MK2',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'revolver',
        weapon = 'WEAPON_REVOLVER',
        label = 'Revolver',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.44 Magnum', item = 'ammo-44' } },
        components = {},
        tint = 0,
    },
    {
        key = 'revolvermk2',
        weapon = 'WEAPON_REVOLVER_MK2',
        label = 'Revolver MK2',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.44 Magnum', item = 'ammo-44' } },
        components = {},
        tint = 0,
    },
    {
        key = 'snspistol',
        weapon = 'WEAPON_SNSPISTOL',
        label = 'SNS Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.45 ACP', item = 'ammo-45' } },
        components = {},
        tint = 0,
    },
    {
        key = 'snspistolmk2',
        weapon = 'WEAPON_SNSPISTOL_MK2',
        label = 'SNS Pistol MK2',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '.45 ACP', item = 'ammo-45' } },
        components = {},
        tint = 0,
    },
    {
        key = 'tecpistol',
        weapon = 'WEAPON_TECPISTOL',
        label = 'Tactical SMG',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'vintagepistol',
        weapon = 'WEAPON_VINTAGEPISTOL',
        label = 'Vintage Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pistolxm3',
        weapon = 'WEAPON_PISTOLXM3',
        label = 'WM 29 Pistol',
        category = 'sidearm',
        enabled = true,
        ammo = { default = 60, options = { 30, 60, 120 }, max = 250 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },

    -- ---- AUTOMATIC -------------------------------------------------
    {
        key = 'advancedrifle',
        weapon = 'WEAPON_ADVANCEDRIFLE',
        label = 'Advanced Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'rifle',
        weapon = 'WEAPON_ASSAULTRIFLE',
        label = 'Assault Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'riflemk2',
        weapon = 'WEAPON_ASSAULTRIFLE_MK2',
        label = 'Assault Rifle MK2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'assaultsmg',
        weapon = 'WEAPON_ASSAULTSMG',
        label = 'Assault SMG',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'battlerifle',
        weapon = 'WEAPON_BATTLERIFLE',
        label = 'Battle Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'bullpuprifle',
        weapon = 'WEAPON_BULLPUPRIFLE',
        label = 'Bullpup Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'bullpupriflemk2',
        weapon = 'WEAPON_BULLPUPRIFLE_MK2',
        label = 'Bullpup Rifle MK2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'carbine',
        weapon = 'WEAPON_CARBINERIFLE',
        label = 'Carbine Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'carbineriflemk2',
        weapon = 'WEAPON_CARBINERIFLE_MK2',
        label = 'Carbine Rifle MK2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'combatmg',
        weapon = 'WEAPON_COMBATMG',
        label = 'Combat MG',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'combatmgmk2',
        weapon = 'WEAPON_COMBATMG_MK2',
        label = 'Combat MG MK2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'combatpdw',
        weapon = 'WEAPON_COMBATPDW',
        label = 'Combat PDW',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'compactrifle',
        weapon = 'WEAPON_COMPACTRIFLE',
        label = 'Compact Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'gusenberg',
        weapon = 'WEAPON_GUSENBERG',
        label = 'Gusenberg',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '.45 ACP', item = 'ammo-45' } },
        components = {},
        tint = 0,
    },
    {
        key = 'heavyrifle',
        weapon = 'WEAPON_HEAVYRIFLE',
        label = 'Heavy Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'mg',
        weapon = 'WEAPON_MG',
        label = 'Machine Gun',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'microsmg',
        weapon = 'WEAPON_MICROSMG',
        label = 'Micro SMG',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '.45 ACP', item = 'ammo-45' } },
        components = {},
        tint = 0,
    },
    {
        key = 'militaryrifle',
        weapon = 'WEAPON_MILITARYRIFLE',
        label = 'Military Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'minismg',
        weapon = 'WEAPON_MINISMG',
        label = 'Mini SMG',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'smg',
        weapon = 'WEAPON_SMG',
        label = 'SMG',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'smgmk2',
        weapon = 'WEAPON_SMG_MK2',
        label = 'SMG Mk2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '9mm', item = 'ammo-9' } },
        components = {},
        tint = 0,
    },
    {
        key = 'specialcarbine',
        weapon = 'WEAPON_SPECIALCARBINE',
        label = 'Special Carbine',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'specialcarbinemk2',
        weapon = 'WEAPON_SPECIALCARBINE_MK2',
        label = 'Special Carbine MK2',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },
    {
        key = 'tacticalrifle',
        weapon = 'WEAPON_TACTICALRIFLE',
        label = 'Tactical Rifle',
        category = 'automatic',
        enabled = true,
        ammo = { default = 150, options = { 60, 150, 300 }, max = 500 },
        ammoTypes = { { key = 'standard', label = '5.56x45', item = 'ammo-rifle' } },
        components = {},
        tint = 0,
    },

    -- ---- SHOTGUN ---------------------------------------------------
    {
        key = 'assaultshotgun',
        weapon = 'WEAPON_ASSAULTSHOTGUN',
        label = 'Assault Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'bullpupshotgun',
        weapon = 'WEAPON_BULLPUPSHOTGUN',
        label = 'Bullpup Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'combatshotgun',
        weapon = 'WEAPON_COMBATSHOTGUN',
        label = 'Combat Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'dbshotgun',
        weapon = 'WEAPON_DBSHOTGUN',
        label = 'Double Barrel Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'heavyshotgun',
        weapon = 'WEAPON_HEAVYSHOTGUN',
        label = 'Heavy Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'shotgun',
        weapon = 'WEAPON_PUMPSHOTGUN',
        label = 'Pump Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'pumpshotgunmk2',
        weapon = 'WEAPON_PUMPSHOTGUN_MK2',
        label = 'Pump Shotgun MK2',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'sawnoffshotgun',
        weapon = 'WEAPON_SAWNOFFSHOTGUN',
        label = 'Sawn Off Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'autoshotgun',
        weapon = 'WEAPON_AUTOSHOTGUN',
        label = 'Sweeper Shotgun',
        category = 'shotgun',
        enabled = true,
        ammo = { default = 40, options = { 20, 40, 80 }, max = 150 },
        ammoTypes = { { key = 'standard', label = '12 Gauge', item = 'ammo-shotgun' } },
        components = {},
        tint = 0,
    },

    -- ---- PRECISION -------------------------------------------------
    {
        key = 'heavysniper',
        weapon = 'WEAPON_HEAVYSNIPER',
        label = 'Heavy Sniper',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '.50 BMG', item = 'ammo-heavysniper' } },
        components = {},
        tint = 0,
    },
    {
        key = 'snipermk2',
        weapon = 'WEAPON_HEAVYSNIPER_MK2',
        label = 'Heavy Sniper MK2',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '.50 BMG', item = 'ammo-heavysniper' } },
        components = {},
        tint = 0,
    },
    {
        key = 'marksman',
        weapon = 'WEAPON_MARKSMANRIFLE',
        label = 'Marksman Rifle',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '7.62x51', item = 'ammo-sniper' } },
        components = {},
        tint = 0,
    },
    {
        key = 'marksmanriflemk2',
        weapon = 'WEAPON_MARKSMANRIFLE_MK2',
        label = 'Marksman Rifle MK2',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '7.62x51', item = 'ammo-sniper' } },
        components = {},
        tint = 0,
    },
    {
        key = 'musket',
        weapon = 'WEAPON_MUSKET',
        label = 'Musket',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '.50 Ball', item = 'ammo-musket' } },
        components = {},
        tint = 0,
    },
    {
        key = 'precisionrifle',
        weapon = 'WEAPON_PRECISIONRIFLE',
        label = 'Precision Rifle',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '7.62x51', item = 'ammo-sniper' } },
        components = {},
        tint = 0,
    },
    {
        key = 'sniper',
        weapon = 'WEAPON_SNIPERRIFLE',
        label = 'Sniper Rifle',
        category = 'precision',
        enabled = true,
        ammo = { default = 20, options = { 10, 20, 40 }, max = 80 },
        ammoTypes = { { key = 'standard', label = '7.62x51', item = 'ammo-sniper' } },
        components = {},
        tint = 0,
    },

    -- ---- HEAVY -----------------------------------------------------
    {
        key = 'emplauncher',
        weapon = 'WEAPON_EMPLAUNCHER',
        label = 'Compact EMP Launcher',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'EMP round', item = 'ammo-emp' } },
        components = {},
        tint = 0,
    },
    {
        key = 'compactlauncher',
        weapon = 'WEAPON_COMPACTLAUNCHER',
        label = 'Compact Grenade Launcher',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = '40mm Explosive', item = 'ammo-grenade' } },
        components = {},
        tint = 0,
    },
    {
        key = 'firework',
        weapon = 'WEAPON_FIREWORK',
        label = 'Firework Launcher',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Firework', item = 'ammo-firework' } },
        components = {},
        tint = 0,
    },
    {
        key = 'fireworksingle',
        weapon = 'WEAPON_FIREWORKSINGLE',
        label = 'Firework Spray',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Firework', item = 'ammo-firework' } },
        components = {},
        tint = 0,
    },
    {
        key = 'flamethrower',
        weapon = 'WEAPON_FLAMETHROWER',
        label = 'Flamethrower',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Fuel', item = 'ammo-flamethrower' } },
        components = {},
        tint = 0,
    },
    {
        key = 'grenadelauncher',
        weapon = 'WEAPON_GRENADELAUNCHER',
        label = 'Grenade Launcher',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = '40mm Explosive', item = 'ammo-grenade' } },
        components = {},
        tint = 0,
    },
    {
        key = 'hominglauncher',
        weapon = 'WEAPON_HOMINGLAUNCHER',
        label = 'Homing Launcher',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Rocket', item = 'ammo-rocket' } },
        components = {},
        tint = 0,
    },
    {
        key = 'minigun',
        weapon = 'WEAPON_MINIGUN',
        label = 'Minigun',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = '7.62x39', item = 'ammo-rifle2' } },
        components = {},
        tint = 0,
    },
    {
        key = 'rpg',
        weapon = 'WEAPON_RPG',
        label = 'RPG',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Rocket', item = 'ammo-rocket' } },
        components = {},
        tint = 0,
    },
    {
        key = 'railgun',
        weapon = 'WEAPON_RAILGUN',
        label = 'Railgun',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Railgun charge', item = 'ammo-railgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'railgunxm3',
        weapon = 'WEAPON_RAILGUNXM3',
        label = 'Railgun XM3',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Railgun charge', item = 'ammo-railgun' } },
        components = {},
        tint = 0,
    },
    {
        key = 'raycarbine',
        weapon = 'WEAPON_RAYCARBINE',
        label = 'Unholy Hellbringer',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Laser charge', item = 'ammo-laser' } },
        components = {},
        tint = 0,
    },
    {
        key = 'rayminigun',
        weapon = 'WEAPON_RAYMINIGUN',
        label = 'Widowmaker',
        category = 'heavy',
        enabled = false,
        ammo = { default = 8, options = { 4, 8, 16 }, max = 30 },
        ammoTypes = { { key = 'standard', label = 'Laser charge', item = 'ammo-laser' } },
        components = {},
        tint = 0,
    },

    -- ---- MELEE -----------------------------------------------------
    {
        key = 'bat',
        weapon = 'WEAPON_BAT',
        label = 'Bat',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'bottle',
        weapon = 'WEAPON_BOTTLE',
        label = 'Bottle',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'crowbar',
        weapon = 'WEAPON_CROWBAR',
        label = 'Crowbar',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'dagger',
        weapon = 'WEAPON_DAGGER',
        label = 'Dagger',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'golfclub',
        weapon = 'WEAPON_GOLFCLUB',
        label = 'Golf Club',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'hammer',
        weapon = 'WEAPON_HAMMER',
        label = 'Hammer',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'hatchet',
        weapon = 'WEAPON_HATCHET',
        label = 'Hatchet',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'knife',
        weapon = 'WEAPON_KNIFE',
        label = 'Knife',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'knuckles',
        weapon = 'WEAPON_KNUCKLE',
        label = 'Knuckle Dusters',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'machete',
        weapon = 'WEAPON_MACHETE',
        label = 'Machete',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'nightstick',
        weapon = 'WEAPON_NIGHTSTICK',
        label = 'Nightstick',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'poolcue',
        weapon = 'WEAPON_POOLCUE',
        label = 'Pool Cue',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'switchblade',
        weapon = 'WEAPON_SWITCHBLADE',
        label = 'Switchblade',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'wrench',
        weapon = 'WEAPON_WRENCH',
        label = 'Wrench',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'battleaxe',
        weapon = 'WEAPON_BATTLEAXE',
        label = 'Battle Axe',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'stonehatchet',
        weapon = 'WEAPON_STONE_HATCHET',
        label = 'Stone Hatchet',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'candycane',
        weapon = 'WEAPON_CANDYCANE',
        label = 'Candy Cane',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
    {
        key = 'flashlight',
        weapon = 'WEAPON_FLASHLIGHT',
        label = 'Flashlight',
        category = 'melee',
        enabled = true,
        ammo = { default = 1, options = nil, max = 1 },
        ammoTypes = false,
        components = {},
        tint = 0,
    },
}
